---
version: '3.7'

services: 

  mysql: 
    image: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file: mysql/default.env
    cap_add:
      - SYS_NICE

  redis:
    image: redis

  fleet: 
    image: fleetdm/fleet
    depends_on:
      - mysql
      - redis
    command: sh -c "/usr/bin/fleet prepare db --no-prompt && /usr/bin/fleet serve"
    env_file: fleet/default.env
    volumes:
      - ./fleet:/fleet/
      - ./fleet/logs:/logs
      - ./fleet/vulndb:/vulndb
    labels:
      traefik.enable: true
      traefik.http.routers.fleet.entrypoints: "websecure"
      traefik.http.routers.fleet.rule: "Host(`fleet.example.com`)"
      traefik.http.services.fleet.loadbalancer.server.port: "8412"
      traefik.http.routers.fleet.tls: true
      traefik.http.routers.fleet.tls.certresolver: "default"
    networks:
      - traefik_proxy
      - default

  traefik:
    image: traefik:v2.7
    container_name: traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik
    # labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.traefik.rule=Host(`traefik.example.com`)"
    #  - "traefik.http.routers.traefik.entrypoints=websecure"
    #  - "traefik.http.routers.traefik.tls.certresolver=default"
    #  - "traefik.http.routers.traefik.service=api@internal"
    #  - "traefik.http.routers.traefik.middlewares=auth@docker"
    #  - "traefik.http.middlewares.auth.basicauth.users=user:pass"
    networks:
      - traefik_proxy
      - default
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true
  default:
    driver: bridge
